title: 我的项目
subtitle: 这里展示了我的一些个人项目和开源贡献

# 指定使用的模板文件名，现有页面模板可见templates\pages
template: projects

categories:
  - name: 个人项目
    icon: fas fa-code
    sites:
      - name: 个人博客
        icon: fas fa-blog
        description: 个人bolg
        url: "https://bento.me/yufengxiang"
      - name: MoonTV
        icon: fas fa-compass
        description: 聚合影视搜索观影平台
        url: "https://itv.mvpbook.cn/"
      - name: LibreTV
        icon: fas fa-tasks
        description: 聚合影视搜索观影平台
        url: "https://ys.mvpbook.cn/"
      - name: 个人图床
        icon: fas fa-blog
        description: 使用telegram搭建的图床
        url: "https://tuku.mvpbook.cn/"
