title: 社区博客
subtitle: 优秀的博主和技术社区

# 指定使用的模板文件名，现有页面模板可见templates\pages
template: Community

categories:
  - name: 优质博主
    icon: fas fa-user-friends
    sites:
      - name: 零度博客
        icon: fas fa-code
        description: 专注于分享免费、实用软件和有趣的网站、探索AI 黑科技与最新前沿的IT技术动态，帮助用户提升技术水平
        url: "https://www.freedidi.com/"
      - name: 悟空百科
        icon: fas fa-paint-brush
        description: 分享各类技术或资源
        url: "https://didiboy0702.gitbook.io/wukongdaily"
      - name: 小张的后端
        icon: fas fa-server
        description: 分享后端开发经验
        url: "#"
  - name: 技术社区
    icon: fas fa-laptop-code
    sites:
      - name: GitHub
        icon: fab fa-github
        description: 开源代码托管平台
        url: https://github.com
      - name: Stack Overflow
        icon: fab fa-stack-overflow
        description: 程序员问答社区
        url: https://stackoverflow.com 
