title: 欢迎使用
subtitle: 个人导航站点

# 指定使用的模板文件名，现有页面模板可见templates\pages
template: tool

categories:
  - name: 在线工具
    icon: fas fa-wrench
    sites:
      - name: 在线屏幕测试
        url: https://lab.luozhinet.com/tool/screentest/
        icon: fa-solid fa-desktop
        description: 在线屏幕测试
      - name: 屏幕测试
        url: https://test.screamingline.com/
        icon: fa-solid fa-circle-half-stroke
        description: 尖叫直线 屏幕测试
  - name: 综合网站
    icon: fas fa-star
    sites:
      - name: Flightradar24
        url: https://www.flightradar24.com/
        icon: fa-solid fa-plane
        description: 在线查看追踪全球航班位置
  - name: 综合网站
    icon: fas fa-star
    sites:
      - name: DNS.fish
        url: https://dns.fish/zh-hans/
        icon: fa-solid fa-globe
        description: 实时DNS查询