title: 资源站
description: 个人网络资源站
author: yufeng
favicon: favicon.ico
logo_text: 资源站

fonts:
  title:
    family: Poppins
    weight: 600
    source: google
  subtitle:
    family: Quicksand
    weight: 500
    source: google
  body:
    family: Noto Sans SC
    weight: 400
    source: google
    
profile:
  title: Hello,
  subtitle: Welcome to My resource centre
  description: 导航菜单

social:
  - name: GitHub
    url: https://github.com
    icon: fab fa-github
  - name: Youtube
    url: https://www.youtube.com/
    icon: fa-brands fa-youtube
  - name: TikTok
    url: https://www.tiktok.com/
    icon: fa-brands fa-tiktok
  - name: Spotify
    url: https://open.spotify.com/
    icon: fa-brands fa-spotify
  - name: Facebook
    url: https://www.facebook.com/
    icon: fa-brands fa-facebook
  - name: Telegram
    url: https://t.me
    icon: fab fa-telegram
  - name: Twitter
    url: https://twitter.com
    icon: fab fa-twitter
  - name: Steam
    url: https://steam.com
    icon: fab fa-steam 
